# Pinterest Pin Template
# Creates vertical pins optimized for Pinterest (1000×1500 recommended)

name: "Pinterest Pin"
description: "Create eye-catching vertical pins for Pinterest (1000×1500, 2:3 aspect ratio)"
version: "1.0.0"
category: "social-media"

# Pipeline: video → vertical crop → text overlay → optimize
pipeline:
  steps:
    - tool: "gifcurry"
      operation: "create_gif"
      input: "{{video_path}}"
      output: "temp_pin.gif"
      params:
        width: 1000
        height: 1500
        start_time: "{{start_time|0}}"
        duration: "{{duration|6}}"
        quality: "{{quality_level}}"
        text_overlay:
          enabled: "{{show_text|true}}"
          text: "{{pin_title|Discover More}}"
          font_size: 64
          font_family: "{{font|Playfair Display}}"
          color: "white"
          position: "top"
          background: "semi-transparent"

    - tool: "gifsicle"
      operation: "optimize"
      input: "temp_pin.gif"
      output: "{{output_path}}"
      params:
        optimization_level: "{{optimization}}"
        colors: 256
        lossy: "{{lossy_amount}}"
        resize: "1000x1500"

# Quality presets optimized for Pinterest
presets:
  quick:
    description: "Fast preview (lower quality, good for testing)"
    quality_level: 70
    optimization: 2
    lossy_amount: 30
    duration: 6
    expected_size: "4-6MB"
    processing_time: "45s"

  standard:
    description: "Balanced quality for most pins (recommended)"
    quality_level: 85
    optimization: 3
    lossy_amount: 20
    duration: 6
    expected_size: "6-10MB"
    processing_time: "90s"

  premium:
    description: "High quality for brand accounts and featured pins"
    quality_level: 95
    optimization: 3
    lossy_amount: 10
    duration: 8
    expected_size: "10-15MB"
    processing_time: "150s"

  story:
    description: "Pinterest Story format (9:16, shorter duration)"
    quality_level: 85
    optimization: 3
    lossy_amount: 20
    duration: 4
    width: 1080
    height: 1920
    expected_size: "5-8MB"
    processing_time: "75s"

# Variable definitions
variables:
  video_path:
    type: "file"
    required: true
    description: "Source video file"

  pin_title:
    type: "string"
    required: false
    default: "Discover More"
    description: "Title text overlay (appears at top)"

  start_time:
    type: "float"
    required: false
    default: 0
    description: "Start time in seconds"

  duration:
    type: "float"
    required: false
    default: 6
    description: "Duration in seconds (Pinterest recommends 6-15s)"

  show_text:
    type: "boolean"
    required: false
    default: true
    description: "Show title text overlay"

  font:
    type: "string"
    required: false
    default: "Playfair Display"
    description: "Font family for title"

# Output validation
validation:
  max_file_size_mb: 20
  min_file_size_mb: 1
  required_dimensions:
    width: 1000
    height: 1500
    aspect_ratio: "2:3"
  duration:
    min: 4
    max: 15
  format: "GIF"

# Platform-specific metadata
platform:
  name: "Pinterest"
  optimal_dimensions: "1000×1500"
  max_file_size: "20MB"
  recommended_duration: "6-15s"
  aspect_ratios:
    - "2:3 (standard pin)"
    - "9:16 (Pinterest Story)"
  notes:
    - "Vertical orientation performs best"
    - "Text overlays increase engagement"
    - "First 2 seconds are critical for stopping scrollers"

# Metadata
tags:
  - pinterest
  - social-media
  - vertical
  - pin
  - inspiration
  - diy
  - recipe
  - fashion

use_cases:
  - "Recipe videos (step-by-step)"
  - "DIY tutorials (crafts, home decor)"
  - "Fashion lookbooks (outfit inspiration)"
  - "Product showcases (e-commerce)"
  - "Travel inspiration (destination highlights)"
  - "Infographic animations (educational)"
