# Instagram Square Demo Template
# Creates 1:1 square GIF optimized for Instagram posts

name: "Instagram Square Demo"
description: "Square (1:1) product demo GIF optimized for Instagram posts and stories"
version: "1.0.0"
category: "social-media"

# Pipeline: video → square crop → text overlay → optimize
pipeline:
  - tool: "gifcurry"
    config:
      start_time: 0
      end_time: 8  # Instagram allows up to 60s, but 8s is optimal
      width: 640   # Square format
      height: 640
      fps: 24      # Higher FPS for Instagram
      quality: 100
      crop_top: 0
      crop_bottom: 0
      crop_left: "{{auto_center}}"  # Auto-center for square
      crop_right: "{{auto_center}}"
      text_overlay:
        text: "{{caption}}"
        position: "center"
        font: "Arial-Bold"
        font_size: 48
        fill_color: [255, 255, 255, 255]
        outline_color: [0, 0, 0, 255]
        outline_size: 4

  - tool: "gifsicle"
    config:
      optimization_level: 3
      colors: 256  # Instagram supports more colors
      lossy: 60    # Less aggressive for quality

assets:
  required:
    - name: "video"
      type: "video/*"
      description: "Product demo or content video"

  optional:
    - name: "logo"
      type: "image/*"
      description: "Brand logo overlay"
    - name: "background"
      type: "image/*"
      description: "Background image for padding"

variables:
  caption:
    type: "string"
    default: "New Product"
    description: "Text caption overlay"

  auto_center:
    type: "string"
    default: "auto"
    description: "Auto-center for square crop"

presets:
  story:  # Instagram Story format
    gifcurry:
      width: 1080
      height: 1920
      fps: 30
    gifsicle:
      colors: 256
      lossy: 40

  post:  # Instagram Post format (default)
    gifcurry:
      width: 640
      height: 640
      fps: 24
    gifsicle:
      colors: 256
      lossy: 60

  feed:  # Smaller for feed scrolling
    gifcurry:
      width: 480
      height: 480
      fps: 20
    gifsicle:
      colors: 128
      lossy: 80

validation:
  max_duration: 60  # Instagram maximum
  max_size_mb: 15   # Instagram GIF limit
  required_format: "gif"
  aspect_ratio: [1, 1]  # Must be square

metadata:
  author: "gif-repos generator"
  tags: [social-media, instagram, square, post, story]
  platform: "instagram"
  use_cases:
    - "Product launches"
    - "Behind-the-scenes"
    - "Quick tips"
    - "Announcements"
    - "User-generated content showcase"
