# Background Removal Template
# AI-powered background removal for product videos, portraits, etc.

name: "AI Background Removal"
description: "Remove backgrounds from videos using AI (perfect for product demos, green screen replacement)"
version: "1.0.0"
category: "ai-enhancement"

# Pipeline: video → AI background segmentation → replace/remove → optimize
pipeline:
  steps:
    - tool: "backgroundremover"
      operation: "remove_background"
      input: "{{video_path}}"
      output: "temp_no_bg.mp4"
      params:
        model: "{{model|u2net}}"
        alpha_matting: "{{alpha_matting|true}}"
        alpha_matting_foreground_threshold: 240
        alpha_matting_background_threshold: 10

    - tool: "ffmpeg"
      operation: "composite_background"
      input: "temp_no_bg.mp4"
      output: "temp_final.mp4"
      params:
        background:
          type: "{{bg_type|transparent}}"
          color: "{{bg_color|#00FF00}}"
          image: "{{bg_image|}}"
          blur: "{{bg_blur|0}}"

    - tool: "gifcurry"
      operation: "convert_to_gif"
      input: "temp_final.mp4"
      output: "temp_output.gif"
      params:
        width: "{{width|800}}"
        height: "{{height|600}}"
        start_time: "{{start_time|0}}"
        duration: "{{duration|5}}"
        quality: 90

    - tool: "gifsicle"
      operation: "optimize"
      input: "temp_output.gif"
      output: "{{output_path}}"
      params:
        optimization_level: 3
        colors: 256
        lossy: 20

# Background removal presets
presets:
  transparent:
    description: "Transparent background (for overlay use)"
    bg_type: "transparent"
    model: "u2net"
    alpha_matting: true
    expected_size: "5-10MB"
    processing_time: "2-4 minutes"
    output_format: "GIF or PNG sequence"

  white:
    description: "Clean white background (product photography style)"
    bg_type: "solid"
    bg_color: "#FFFFFF"
    model: "u2net"
    alpha_matting: true
    expected_size: "4-8MB"
    processing_time: "2-4 minutes"

  blur:
    description: "Blurred original background (portrait mode effect)"
    bg_type: "blur"
    bg_blur: 50
    model: "u2netp"
    alpha_matting: true
    expected_size: "6-10MB"
    processing_time: "2-4 minutes"

  custom:
    description: "Custom background image replacement"
    bg_type: "image"
    model: "u2net"
    alpha_matting: true
    expected_size: "7-12MB"
    processing_time: "2-4 minutes"

  green-screen:
    description: "Green screen replacement (for video editing)"
    bg_type: "solid"
    bg_color: "#00FF00"
    model: "u2net"
    alpha_matting: false
    expected_size: "5-9MB"
    processing_time: "2-3 minutes"

# Variable definitions
variables:
  video_path:
    type: "file"
    required: true
    description: "Source video file"

  bg_type:
    type: "string"
    required: false
    default: "transparent"
    options: ["transparent", "solid", "blur", "image"]
    description: "Background type"

  bg_color:
    type: "string"
    required: false
    default: "#FFFFFF"
    description: "Background color (hex code) for solid backgrounds"

  bg_image:
    type: "file"
    required: false
    description: "Custom background image path"

  bg_blur:
    type: "integer"
    required: false
    default: 0
    description: "Blur amount for original background (0-100)"

  model:
    type: "string"
    required: false
    default: "u2net"
    options: ["u2net", "u2netp", "silueta"]
    description: "AI model for background removal"

  alpha_matting:
    type: "boolean"
    required: false
    default: true
    description: "Use alpha matting for better edge quality"

  duration:
    type: "float"
    required: false
    default: 5
    description: "Duration in seconds"

# Output validation
validation:
  max_file_size_mb: 20
  duration:
    min: 1
    max: 30
  format: "GIF or MP4"

# AI model information
models:
  u2net:
    name: "U^2-Net"
    description: "High accuracy, slower processing"
    accuracy: "95%+"
    speed: "Slow"
    best_for: "Products, portraits, complex scenes"

  u2netp:
    name: "U^2-Net (lightweight)"
    description: "Faster processing, good accuracy"
    accuracy: "90%+"
    speed: "Fast"
    best_for: "Simple subjects, real-time needs"

  silueta:
    name: "Silueta"
    description: "Specialized for portraits"
    accuracy: "97%+ for people"
    speed: "Medium"
    best_for: "Portraits, people-focused content"

# Metadata
tags:
  - ai
  - background-removal
  - green-screen
  - transparent
  - product-photography
  - portrait
  - compositing

use_cases:
  - "Product demonstration videos (clean background)"
  - "Portrait videos (professional look)"
  - "Green screen replacement"
  - "E-commerce product videos"
  - "Social media content (transparent overlays)"
  - "Video thumbnails with custom backgrounds"
  - "Presentation materials"
  - "Educational content (focus on subject)"

background_options:
  transparent:
    description: "Subject only, no background"
    use_cases: ["Overlays", "Compositing", "Web design"]
    formats: ["PNG sequence", "GIF with transparency"]

  solid_color:
    description: "Clean, consistent color"
    use_cases: ["Product photography", "Professional videos"]
    popular_colors: ["White (#FFFFFF)", "Black (#000000)", "Brand colors"]

  blur:
    description: "Blurred original background"
    use_cases: ["Portraits", "Depth effect", "Focus on subject"]
    blur_levels: ["Subtle (20)", "Medium (50)", "Heavy (80)"]

  custom_image:
    description: "Replace with custom background"
    use_cases: ["Virtual sets", "Creative composites", "Brand environments"]
    tips: ["Match lighting", "Consistent perspective", "Color grade to match"]

best_practices:
  - "Use u2net for highest quality"
  - "Enable alpha matting for smoother edges"
  - "Ensure good lighting on subject"
  - "Avoid busy backgrounds in original footage"
  - "Green/blue screen works best for live action"
  - "Test with a frame before processing entire video"
  - "Higher resolution = better edge detection"

common_issues:
  hair_fringing:
    solution: "Enable alpha matting, use higher threshold"

  shadows_removed:
    solution: "Use blur background instead of removal"

  subject_partially_removed:
    solution: "Improve lighting, avoid colors similar to background"

  slow_processing:
    solution: "Use u2netp model or reduce resolution"

hardware_requirements:
  minimum:
    gpu: "4GB VRAM or CPU with 8GB RAM"
    processing_time: "5-10 minutes per minute of video"

  recommended:
    gpu: "8GB+ VRAM (NVIDIA CUDA)"
    processing_time: "1-3 minutes per minute of video"
