/**
 * Default Presets
 * Curated animation presets for each animation type
 */

import type { Preset } from "../types/preset";

// Matrix Presets
export const matrixPresets: Preset[] = [
  {
    id: "matrix-classic",
    name: "Classic Green",
    description: "Original Matrix falling code",
    animationType: "matrix",
    config: {
      speed: 50,
      color: "#00ff41",
      density: 50,
      glow: 30,
      fontSize: 16,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "matrix-blue",
    name: "Blue Code",
    description: "Cool blue cyberpunk vibe",
    animationType: "matrix",
    config: {
      speed: 60,
      color: "#00d9ff",
      density: 70,
      glow: 50,
      fontSize: 14,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "matrix-red",
    name: "Red Alert",
    description: "Warning system theme",
    animationType: "matrix",
    config: {
      speed: 80,
      color: "#ff0055",
      density: 80,
      glow: 70,
      fontSize: 18,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "matrix-slow",
    name: "Slow Rain",
    description: "Relaxed, meditative flow",
    animationType: "matrix",
    config: {
      speed: 20,
      color: "#00ff88",
      density: 30,
      glow: 20,
      fontSize: 20,
      fps: 30,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Fluid Presets
export const fluidPresets: Preset[] = [
  {
    id: "fluid-purple",
    name: "Purple Dream",
    description: "Deep purple psychedelic",
    animationType: "fluid",
    config: {
      speed: 30,
      color1: "#b565d8",
      color2: "#7b2cbf",
      complexity: 50,
      blur: 20,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fluid-ocean",
    name: "Ocean Waves",
    description: "Blue aquatic motion",
    animationType: "fluid",
    config: {
      speed: 25,
      color1: "#00d9ff",
      color2: "#4169e1",
      complexity: 40,
      blur: 30,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fluid-sunset",
    name: "Sunset Glow",
    description: "Warm orange and pink",
    animationType: "fluid",
    config: {
      speed: 20,
      color1: "#ff6b35",
      color2: "#ff00ff",
      complexity: 60,
      blur: 25,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fluid-fast",
    name: "Rapid Flow",
    description: "High-speed morphing",
    animationType: "fluid",
    config: {
      speed: 70,
      color1: "#00ff00",
      color2: "#ffff00",
      complexity: 80,
      blur: 15,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Aurora Presets
export const auroraPresets: Preset[] = [
  {
    id: "aurora-classic",
    name: "Northern Lights",
    description: "Classic aurora borealis",
    animationType: "aurora",
    config: {
      speed: 40,
      color1: "#00ff87",
      color2: "#60efff",
      color3: "#ff00ff",
      intensity: 70,
      waves: 5,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "aurora-cosmic",
    name: "Cosmic Dance",
    description: "Deep space aurora",
    animationType: "aurora",
    config: {
      speed: 30,
      color1: "#9d4edd",
      color2: "#ff006e",
      color3: "#00d9ff",
      intensity: 80,
      waves: 7,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "aurora-ethereal",
    name: "Ethereal",
    description: "Soft, gentle waves",
    animationType: "aurora",
    config: {
      speed: 20,
      color1: "#a8dadc",
      color2: "#457b9d",
      color3: "#1d3557",
      intensity: 50,
      waves: 3,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "aurora-intense",
    name: "Solar Storm",
    description: "Intense, bright aurora",
    animationType: "aurora",
    config: {
      speed: 70,
      color1: "#ff0000",
      color2: "#ffff00",
      color3: "#00ff00",
      intensity: 95,
      waves: 8,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Particle Presets
export const particlePresets: Preset[] = [
  {
    id: "particle-constellation",
    name: "Constellation",
    description: "Classic connected stars",
    animationType: "particle",
    config: {
      speed: 50,
      color: "#00d9ff",
      count: 150,
      size: 3,
      connectionDistance: 150,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "particle-dense",
    name: "Dense Network",
    description: "Heavily connected mesh",
    animationType: "particle",
    config: {
      speed: 30,
      color: "#00ff00",
      count: 300,
      size: 2,
      connectionDistance: 120,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "particle-sparse",
    name: "Sparse Stars",
    description: "Minimal, elegant",
    animationType: "particle",
    config: {
      speed: 40,
      color: "#ffffff",
      count: 80,
      size: 4,
      connectionDistance: 200,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "particle-energy",
    name: "Energy Field",
    description: "Fast, high-energy",
    animationType: "particle",
    config: {
      speed: 80,
      color: "#ff00ff",
      count: 200,
      size: 5,
      connectionDistance: 100,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Glitch Presets
export const glitchPresets: Preset[] = [
  {
    id: "glitch-cyberpunk",
    name: "Cyberpunk",
    description: "Classic RGB split",
    animationType: "glitch",
    config: {
      intensity: 50,
      color1: "#ff0080",
      color2: "#00ffff",
      frequency: 30,
      blockSize: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "glitch-subtle",
    name: "Subtle Shift",
    description: "Minimal, classy glitch",
    animationType: "glitch",
    config: {
      intensity: 20,
      color1: "#0000ff",
      color2: "#ff0000",
      frequency: 15,
      blockSize: 30,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "glitch-chaos",
    name: "Intense Chaos",
    description: "Maximum disruption",
    animationType: "glitch",
    config: {
      intensity: 90,
      color1: "#ff00ff",
      color2: "#00ff00",
      frequency: 70,
      blockSize: 80,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "glitch-retro",
    name: "Retro TV",
    description: "Vintage broadcast",
    animationType: "glitch",
    config: {
      intensity: 40,
      color1: "#ffff00",
      color2: "#00ffff",
      frequency: 25,
      blockSize: 60,
      fps: 30,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Neon Trails Presets
export const neonTrailsPresets: Preset[] = [
  {
    id: "neon-tron",
    name: "Fast Tron",
    description: "Classic high-speed grid",
    animationType: "neonTrails",
    config: {
      speed: 60,
      color: "#ff00d9",
      trailLength: 100,
      count: 15,
      width: 3,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "neon-slow",
    name: "Slow Grid",
    description: "Meditative light paths",
    animationType: "neonTrails",
    config: {
      speed: 30,
      color: "#00d9ff",
      trailLength: 150,
      count: 10,
      width: 4,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "neon-rainbow",
    name: "Rainbow Trails",
    description: "Vibrant multi-color",
    animationType: "neonTrails",
    config: {
      speed: 50,
      color: "#00ff00",
      trailLength: 120,
      count: 20,
      width: 2,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "neon-dense",
    name: "Dense Highway",
    description: "Many fast trails",
    animationType: "neonTrails",
    config: {
      speed: 70,
      color: "#ffff00",
      trailLength: 80,
      count: 30,
      width: 2,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Morph Blob Presets
export const morphBlobPresets: Preset[] = [
  {
    id: "blob-purple",
    name: "Purple Morph",
    description: "Smooth purple organic blob",
    animationType: "morphBlob",
    config: {
      speed: 40,
      color: "#b565d8",
      complexity: 12,
      size: 200,
      glow: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "blob-green",
    name: "Bio Blob",
    description: "Organic green life form",
    animationType: "morphBlob",
    config: {
      speed: 30,
      color: "#00ff87",
      complexity: 15,
      size: 250,
      glow: 70,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "blob-fast",
    name: "Rapid Morph",
    description: "Fast shape-shifting",
    animationType: "morphBlob",
    config: {
      speed: 70,
      color: "#ff006e",
      complexity: 8,
      size: 180,
      glow: 40,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "blob-large",
    name: "Mega Blob",
    description: "Large glowing mass",
    animationType: "morphBlob",
    config: {
      speed: 20,
      color: "#00d9ff",
      complexity: 18,
      size: 300,
      glow: 80,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Cosmic Presets
export const cosmicPresets: Preset[] = [
  {
    id: "cosmic-nebula",
    name: "Deep Nebula",
    description: "Purple cosmic nebula",
    animationType: "cosmic",
    config: {
      speed: 30,
      color1: "#b565d8",
      color2: "#7b2cbf",
      starCount: 500,
      nebulaIntensity: 60,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "cosmic-starfield",
    name: "Star Field",
    description: "Dense star cluster",
    animationType: "cosmic",
    config: {
      speed: 40,
      color1: "#4169e1",
      color2: "#00d9ff",
      starCount: 800,
      nebulaIntensity: 30,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "cosmic-pink",
    name: "Pink Galaxy",
    description: "Vibrant pink nebula",
    animationType: "cosmic",
    config: {
      speed: 25,
      color1: "#ff006e",
      color2: "#ff00d9",
      starCount: 600,
      nebulaIntensity: 75,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "cosmic-green",
    name: "Alien Sky",
    description: "Mysterious green cosmos",
    animationType: "cosmic",
    config: {
      speed: 35,
      color1: "#00ff87",
      color2: "#00ff41",
      starCount: 400,
      nebulaIntensity: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// DNA Helix Presets
export const dnaHelixPresets: Preset[] = [
  {
    id: "dna-classic",
    name: "Classic DNA",
    description: "Traditional double helix colors",
    animationType: "dnaHelix",
    config: {
      speed: 40,
      color1: "#00ff87",
      color2: "#ff0080",
      helixRadius: 100,
      turns: 3,
      segments: 150,
      glowIntensity: 60,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "dna-cyber",
    name: "Cyber Helix",
    description: "Neon cyberpunk DNA",
    animationType: "dnaHelix",
    config: {
      speed: 60,
      color1: "#00d9ff",
      color2: "#ff00d9",
      helixRadius: 80,
      turns: 4,
      segments: 200,
      glowIntensity: 80,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "dna-wide",
    name: "Wide Spiral",
    description: "Large, slow rotation",
    animationType: "dnaHelix",
    config: {
      speed: 25,
      color1: "#b565d8",
      color2: "#7b2cbf",
      helixRadius: 150,
      turns: 2,
      segments: 120,
      glowIntensity: 40,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "dna-fast",
    name: "Rapid Helix",
    description: "Fast spinning DNA",
    animationType: "dnaHelix",
    config: {
      speed: 80,
      color1: "#ff006e",
      color2: "#00ff41",
      helixRadius: 70,
      turns: 5,
      segments: 250,
      glowIntensity: 70,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Wave Interference Presets
export const waveInterferencePresets: Preset[] = [
  {
    id: "wave-double-slit",
    name: "Double Slit",
    description: "Classic two-source interference",
    animationType: "waveInterference",
    config: {
      speed: 50,
      color1: "#0a0e0a",
      color2: "#00d9ff",
      wavelength: 80,
      amplitude: 50,
      sourceCount: 2,
      resolution: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "wave-ripple",
    name: "Single Ripple",
    description: "Concentric waves from center",
    animationType: "waveInterference",
    config: {
      speed: 40,
      color1: "#0a0e0a",
      color2: "#00ff87",
      wavelength: 60,
      amplitude: 60,
      sourceCount: 1,
      resolution: 60,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "wave-complex",
    name: "Complex Pattern",
    description: "Multi-source interference",
    animationType: "waveInterference",
    config: {
      speed: 60,
      color1: "#0a0e0a",
      color2: "#ff00d9",
      wavelength: 50,
      amplitude: 70,
      sourceCount: 5,
      resolution: 40,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "wave-high-res",
    name: "High Detail",
    description: "Detailed wave interference",
    animationType: "waveInterference",
    config: {
      speed: 30,
      color1: "#0a0e0a",
      color2: "#b565d8",
      wavelength: 100,
      amplitude: 40,
      sourceCount: 3,
      resolution: 80,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Plasma Presets
export const plasmaPresets: Preset[] = [
  {
    id: "plasma-classic",
    name: "Classic Plasma",
    description: "Retro demo scene effect",
    animationType: "plasma",
    config: {
      speed: 50,
      color1: "#ff0080",
      color2: "#7b2cbf",
      color3: "#00d9ff",
      intensity: 80,
      complexity: 60,
      scale: 100,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "plasma-fire",
    name: "Fire Plasma",
    description: "Hot flame colors",
    animationType: "plasma",
    config: {
      speed: 65,
      color1: "#ff0000",
      color2: "#ff6600",
      color3: "#ffff00",
      intensity: 90,
      complexity: 70,
      scale: 80,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "plasma-ocean",
    name: "Ocean Plasma",
    description: "Deep water colors",
    animationType: "plasma",
    config: {
      speed: 35,
      color1: "#0a0e0a",
      color2: "#00d9ff",
      color3: "#4169e1",
      intensity: 70,
      complexity: 50,
      scale: 120,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "plasma-psychedelic",
    name: "Psychedelic",
    description: "High intensity chaos",
    animationType: "plasma",
    config: {
      speed: 80,
      color1: "#ff00d9",
      color2: "#00ff87",
      color3: "#ff006e",
      intensity: 100,
      complexity: 90,
      scale: 60,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Fractal Presets
export const fractalPresets: Preset[] = [
  {
    id: "fractal-mandelbrot",
    name: "Mandelbrot Set",
    description: "Classic fractal visualization",
    animationType: "fractal",
    config: {
      speed: 1.0,
      color1: "#00d9ff",
      color2: "#b565d8",
      color3: "#ff0080",
      fractalType: "mandelbrot",
      maxIterations: 200,
      zoom: 1.0,
      centerX: -0.5,
      centerY: 0.0,
      colorShift: 30,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fractal-julia",
    name: "Julia Set",
    description: "Beautiful Julia fractal",
    animationType: "fractal",
    config: {
      speed: 1.2,
      color1: "#ff006e",
      color2: "#00ff87",
      color3: "#00d9ff",
      fractalType: "julia",
      maxIterations: 150,
      zoom: 1.0,
      centerX: 0.0,
      centerY: 0.0,
      colorShift: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fractal-zoom",
    name: "Deep Zoom",
    description: "Zoomed into fractal detail",
    animationType: "fractal",
    config: {
      speed: 0.8,
      color1: "#00ff41",
      color2: "#00d9ff",
      color3: "#7b2cbf",
      fractalType: "mandelbrot",
      maxIterations: 300,
      zoom: 100,
      centerX: -0.7,
      centerY: 0.0,
      colorShift: 20,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fractal-psychedelic",
    name: "Psychedelic",
    description: "Vibrant color shifts",
    animationType: "fractal",
    config: {
      speed: 1.5,
      color1: "#ff00d9",
      color2: "#00ff87",
      color3: "#ffff00",
      fractalType: "mandelbrot",
      maxIterations: 250,
      zoom: 2.0,
      centerX: -0.5,
      centerY: 0.0,
      colorShift: 80,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Lightning Presets
export const lightningPresets: Preset[] = [
  {
    id: "lightning-storm",
    name: "Thunder Storm",
    description: "Classic electric lightning",
    animationType: "lightning",
    config: {
      speed: 1.0,
      color1: "#00d9ff",
      color2: "#60efff",
      boltCount: 3,
      branchProbability: 40,
      thickness: 3,
      glowIntensity: 60,
      segments: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "lightning-purple",
    name: "Purple Lightning",
    description: "Magical purple bolts",
    animationType: "lightning",
    config: {
      speed: 1.2,
      color1: "#b565d8",
      color2: "#ff00d9",
      boltCount: 5,
      branchProbability: 60,
      thickness: 2,
      glowIntensity: 80,
      segments: 60,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "lightning-red",
    name: "Red Lightning",
    description: "Angry red electric",
    animationType: "lightning",
    config: {
      speed: 1.5,
      color1: "#ff0055",
      color2: "#ff6600",
      boltCount: 7,
      branchProbability: 80,
      thickness: 4,
      glowIntensity: 70,
      segments: 40,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "lightning-minimal",
    name: "Single Strike",
    description: "Clean single bolt",
    animationType: "lightning",
    config: {
      speed: 0.8,
      color1: "#ffffff",
      color2: "#00d9ff",
      boltCount: 1,
      branchProbability: 20,
      thickness: 5,
      glowIntensity: 90,
      segments: 70,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Tessellation Presets
export const tessellationPresets: Preset[] = [
  {
    id: "tessellation-voronoi",
    name: "Voronoi Cells",
    description: "Classic tessellation pattern",
    animationType: "tessellation",
    config: {
      speed: 1.0,
      color1: "#b565d8",
      color2: "#00d9ff",
      cellCount: 30,
      cellMovement: 30,
      borderWidth: 2,
      borderColor: "#0a0e0a",
      colorVariation: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "tessellation-organic",
    name: "Organic Flow",
    description: "Flowing cellular pattern",
    animationType: "tessellation",
    config: {
      speed: 1.5,
      color1: "#00ff87",
      color2: "#00d9ff",
      cellCount: 50,
      cellMovement: 60,
      borderWidth: 1,
      borderColor: "#0a0e0a",
      colorVariation: 70,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "tessellation-honeycomb",
    name: "Honeycomb",
    description: "Static geometric cells",
    animationType: "tessellation",
    config: {
      speed: 0.5,
      color1: "#ffff00",
      color2: "#ff6600",
      cellCount: 40,
      cellMovement: 10,
      borderWidth: 3,
      borderColor: "#000000",
      colorVariation: 30,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "tessellation-cosmic",
    name: "Cosmic Cells",
    description: "Space-themed tessellation",
    animationType: "tessellation",
    config: {
      speed: 0.8,
      color1: "#7b2cbf",
      color2: "#ff00d9",
      cellCount: 20,
      cellMovement: 20,
      borderWidth: 4,
      borderColor: "#0a0e0a",
      colorVariation: 80,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Fire Presets
export const firePresets: Preset[] = [
  {
    id: "fire-classic",
    name: "Classic Fire",
    description: "Realistic campfire",
    animationType: "fire",
    config: {
      speed: 1.0,
      color1: "#ffff00",
      color2: "#ff6600",
      color3: "#ff0000",
      particleCount: 500,
      intensity: 70,
      windSpeed: 0,
      smokeAmount: 30,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fire-blue",
    name: "Blue Flame",
    description: "Hot blue fire",
    animationType: "fire",
    config: {
      speed: 1.2,
      color1: "#ffffff",
      color2: "#00d9ff",
      color3: "#4169e1",
      particleCount: 700,
      intensity: 90,
      windSpeed: 0,
      smokeAmount: 20,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fire-green",
    name: "Mystical Fire",
    description: "Magical green flames",
    animationType: "fire",
    config: {
      speed: 0.8,
      color1: "#00ff41",
      color2: "#00ff87",
      color3: "#00d9ff",
      particleCount: 600,
      intensity: 60,
      windSpeed: 0,
      smokeAmount: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fire-windy",
    name: "Windy Fire",
    description: "Fire blown by wind",
    animationType: "fire",
    config: {
      speed: 1.3,
      color1: "#ff6600",
      color2: "#ff0000",
      color3: "#990000",
      particleCount: 800,
      intensity: 80,
      windSpeed: 60,
      smokeAmount: 40,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Export all presets
export const allDefaultPresets = {
  matrix: matrixPresets,
  fluid: fluidPresets,
  aurora: auroraPresets,
  particle: particlePresets,
  glitch: glitchPresets,
  neonTrails: neonTrailsPresets,
  morphBlob: morphBlobPresets,
  cosmic: cosmicPresets,
  dnaHelix: dnaHelixPresets,
  waveInterference: waveInterferencePresets,
  plasma: plasmaPresets,
  fractal: fractalPresets,
  lightning: lightningPresets,
  tessellation: tessellationPresets,
  fire: firePresets,
};
