/**
 * Default Presets
 * Curated animation presets for each animation type
 */

import type { Preset } from "../types/preset";

// Matrix Presets
export const matrixPresets: Preset[] = [
  {
    id: "matrix-classic",
    name: "Classic Green",
    description: "Original Matrix falling code",
    animationType: "matrix",
    config: {
      speed: 50,
      color: "#00ff41",
      density: 50,
      glow: 30,
      fontSize: 16,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "matrix-blue",
    name: "Blue Code",
    description: "Cool blue cyberpunk vibe",
    animationType: "matrix",
    config: {
      speed: 60,
      color: "#00d9ff",
      density: 70,
      glow: 50,
      fontSize: 14,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "matrix-red",
    name: "Red Alert",
    description: "Warning system theme",
    animationType: "matrix",
    config: {
      speed: 80,
      color: "#ff0055",
      density: 80,
      glow: 70,
      fontSize: 18,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "matrix-slow",
    name: "Slow Rain",
    description: "Relaxed, meditative flow",
    animationType: "matrix",
    config: {
      speed: 20,
      color: "#00ff88",
      density: 30,
      glow: 20,
      fontSize: 20,
      fps: 30,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Fluid Presets
export const fluidPresets: Preset[] = [
  {
    id: "fluid-purple",
    name: "Purple Dream",
    description: "Deep purple psychedelic",
    animationType: "fluid",
    config: {
      speed: 30,
      color1: "#b565d8",
      color2: "#7b2cbf",
      complexity: 50,
      blur: 20,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fluid-ocean",
    name: "Ocean Waves",
    description: "Blue aquatic motion",
    animationType: "fluid",
    config: {
      speed: 25,
      color1: "#00d9ff",
      color2: "#4169e1",
      complexity: 40,
      blur: 30,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fluid-sunset",
    name: "Sunset Glow",
    description: "Warm orange and pink",
    animationType: "fluid",
    config: {
      speed: 20,
      color1: "#ff6b35",
      color2: "#ff00ff",
      complexity: 60,
      blur: 25,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "fluid-fast",
    name: "Rapid Flow",
    description: "High-speed morphing",
    animationType: "fluid",
    config: {
      speed: 70,
      color1: "#00ff00",
      color2: "#ffff00",
      complexity: 80,
      blur: 15,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Aurora Presets
export const auroraPresets: Preset[] = [
  {
    id: "aurora-classic",
    name: "Northern Lights",
    description: "Classic aurora borealis",
    animationType: "aurora",
    config: {
      speed: 40,
      color1: "#00ff87",
      color2: "#60efff",
      color3: "#ff00ff",
      intensity: 70,
      waves: 5,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "aurora-cosmic",
    name: "Cosmic Dance",
    description: "Deep space aurora",
    animationType: "aurora",
    config: {
      speed: 30,
      color1: "#9d4edd",
      color2: "#ff006e",
      color3: "#00d9ff",
      intensity: 80,
      waves: 7,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "aurora-ethereal",
    name: "Ethereal",
    description: "Soft, gentle waves",
    animationType: "aurora",
    config: {
      speed: 20,
      color1: "#a8dadc",
      color2: "#457b9d",
      color3: "#1d3557",
      intensity: 50,
      waves: 3,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "aurora-intense",
    name: "Solar Storm",
    description: "Intense, bright aurora",
    animationType: "aurora",
    config: {
      speed: 70,
      color1: "#ff0000",
      color2: "#ffff00",
      color3: "#00ff00",
      intensity: 95,
      waves: 8,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Particle Presets
export const particlePresets: Preset[] = [
  {
    id: "particle-constellation",
    name: "Constellation",
    description: "Classic connected stars",
    animationType: "particle",
    config: {
      speed: 50,
      color: "#00d9ff",
      count: 150,
      size: 3,
      connectionDistance: 150,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "particle-dense",
    name: "Dense Network",
    description: "Heavily connected mesh",
    animationType: "particle",
    config: {
      speed: 30,
      color: "#00ff00",
      count: 300,
      size: 2,
      connectionDistance: 120,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "particle-sparse",
    name: "Sparse Stars",
    description: "Minimal, elegant",
    animationType: "particle",
    config: {
      speed: 40,
      color: "#ffffff",
      count: 80,
      size: 4,
      connectionDistance: 200,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "particle-energy",
    name: "Energy Field",
    description: "Fast, high-energy",
    animationType: "particle",
    config: {
      speed: 80,
      color: "#ff00ff",
      count: 200,
      size: 5,
      connectionDistance: 100,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Glitch Presets
export const glitchPresets: Preset[] = [
  {
    id: "glitch-cyberpunk",
    name: "Cyberpunk",
    description: "Classic RGB split",
    animationType: "glitch",
    config: {
      intensity: 50,
      color1: "#ff0080",
      color2: "#00ffff",
      frequency: 30,
      blockSize: 50,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "glitch-subtle",
    name: "Subtle Shift",
    description: "Minimal, classy glitch",
    animationType: "glitch",
    config: {
      intensity: 20,
      color1: "#0000ff",
      color2: "#ff0000",
      frequency: 15,
      blockSize: 30,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "glitch-chaos",
    name: "Intense Chaos",
    description: "Maximum disruption",
    animationType: "glitch",
    config: {
      intensity: 90,
      color1: "#ff00ff",
      color2: "#00ff00",
      frequency: 70,
      blockSize: 80,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "glitch-retro",
    name: "Retro TV",
    description: "Vintage broadcast",
    animationType: "glitch",
    config: {
      intensity: 40,
      color1: "#ffff00",
      color2: "#00ffff",
      frequency: 25,
      blockSize: 60,
      fps: 30,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Neon Trails Presets
export const neonTrailsPresets: Preset[] = [
  {
    id: "neon-tron",
    name: "Fast Tron",
    description: "Classic high-speed grid",
    animationType: "neonTrails",
    config: {
      speed: 60,
      color: "#ff00d9",
      trailLength: 100,
      count: 15,
      width: 3,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "neon-slow",
    name: "Slow Grid",
    description: "Meditative light paths",
    animationType: "neonTrails",
    config: {
      speed: 30,
      color: "#00d9ff",
      trailLength: 150,
      count: 10,
      width: 4,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "neon-rainbow",
    name: "Rainbow Trails",
    description: "Vibrant multi-color",
    animationType: "neonTrails",
    config: {
      speed: 50,
      color: "#00ff00",
      trailLength: 120,
      count: 20,
      width: 2,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
  {
    id: "neon-dense",
    name: "Dense Highway",
    description: "Many fast trails",
    animationType: "neonTrails",
    config: {
      speed: 70,
      color: "#ffff00",
      trailLength: 80,
      count: 30,
      width: 2,
      fps: 60,
    },
    createdAt: Date.now(),
    isDefault: true,
  },
];

// Export all presets
export const allDefaultPresets = {
  matrix: matrixPresets,
  fluid: fluidPresets,
  aurora: auroraPresets,
  particle: particlePresets,
  glitch: glitchPresets,
  neonTrails: neonTrailsPresets,
  morphBlob: [],
  cosmic: [],
};
